# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-19 05:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='organizers',
            field=models.ManyToManyField(blank=True, help_text=b'(Organizers allowed to view this queue when they assign their competition to a queue)', related_name='organizers', to=settings.AUTH_USER_MODEL),
        ),
    ]
