# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=b'Date of creation')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name=b'Date of last update')),
                ('status', models.PositiveIntegerField(db_index=True, default=0, verbose_name=b'Status')),
                ('task_type', models.CharField(max_length=256, verbose_name=b'Task type')),
                ('task_args_json', models.TextField(blank=True, verbose_name=b'JSON-encoded task arguments')),
                ('task_info_json', models.TextField(blank=True, verbose_name=b'JSON-encoded task information')),
            ],
        ),
    ]
