#!/bin/bash

THIS_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
pushd `pwd` > /dev/null
cd $THIS_DIR

source ./config/generated/startup_env.sh
echo " .... "
echo "$DJANGO_CONFIGURATION Configuration"
echo " .... "
/bin/bash manage runserver "$@"
popd
