from django.conf.urls import include, url

from .. import views

urlpatterns = [
    url(r'^$', views.competition_index, name='list'),
    url(r'^(?P<pk>\d+)$', views.CompetitionDetailView.as_view(), name='view'),
    url(r'^create$', views.CompetitionUpload.as_view(), name='create'),
    url(r'^s3_create_competition$', views.CompetitionS3Upload.as_view(), name='s3_create_competition'),
    url(r'^edit_competition/(?P<pk>\d+)$', views.CompetitionEdit.as_view(), name='edit'),
    url(r'^delete_competition/(?P<pk>\d+)$', views.CompetitionDelete.as_view(), name='delete'),
    url(r'^(?P<id>\d+)/submissions/(?P<phase>\d+)$', views.CompetitionSubmissionsPage.as_view(), name='competition_submissions_page'),
    url(r'^(?P<competition_id>\d+)/submission_metadata/(?P<phase_id>\d+)$', views.competition_submission_metadata_page, name='competition_submissions_metadata'),
    url(r'^(?P<id>\d+)/results/(?P<phase>\d+)$', views.CompetitionResultsPage.as_view(), name='competition_results_page'),
    url(r'^competition/submission/(?P<submission_id>\d+)/(?P<filetype>detailed_results.html)$',
        views.MyCompetitionSubmissionOutput.as_view(),
        name='my_competition_output'),
    url(r'^(?P<id>\d+)/results/(?P<phase>\d+)/data$', views.CompetitionResultsDownload.as_view(), name='competition_results_download'),
    url(r'^(?P<id>\d+)/results_complete/(?P<phase>\d+)/data$', views.CompetitionCompleteResultsDownload.as_view(), name='competition_results_complete_download'),
    url(r'^message_participants/(?P<competition_id>\d+)', views.competition_message_participants, name="competition_message_participants"),
    url(r'^submission_delete/(?P<pk>\d+)', views.SubmissionDelete.as_view(), name="submission_delete"),
    url(r'^download_yaml/(?P<competition_pk>\d+)', views.download_competition_yaml, name="download_yaml"),
    url(r'^make_modified_bundle/(?P<competition_pk>\d+)/', views.start_make_bundle_task, name="make_bundle"),
    url(r'^download/(?P<competition_pk>\d+)', views.download_competition_bundle, name="download"),
    url(r'^download_leaderboard_results/(?P<competition_pk>\d+)/(?P<phase_pk>\d+)', views.download_leaderboard_results, name="download_leaderboard_results"),
    url(r'^update_description/(?P<submission_pk>\d+)', views.submission_update_description, name="submission_update_description"),
    url(r'^mark_as_failed/(?P<submission_pk>\d+)', views.submission_mark_as_failed, name="submission_mark_as_failed"),
    url(r'^toggle_leaderboard/(?P<submission_pk>\d+)', views.submission_toggle_leaderboard, name="submission_toggle_leaderboard"),
    url(r'^submission_re_run/(?P<submission_pk>\d+)', views.submission_re_run, name="submission_re_run"),
    url(r'^submission_re_run_all/(?P<phase_pk>\d+)', views.submission_re_run_all, name="submission_re_run_all"),
    url(r'^submission_migrate/(?P<pk>\d+)', views.submission_migrate, name="submission_migrate"),
    url(r'^public_submissions/(?P<pk>\d+)$', views.CompetitionPublicSubmission.as_view(), name='public_submissions'),
    url(r'^(?P<pk>\d+)/public_submissions/(?P<phase>\d+)$', views.CompetitionPublicSubmissionByPhases.as_view(), name='public_submissions_phase'),
    url(r'^(?P<competition_pk>\d+)/dumps/$', views.competition_dumps_view, name='dumps'),
    url(r'^(?P<pk>\d+)/delete_dump/$', views.CompetitionDumpDeleteView.as_view(), name="delete_dump"),
    url(r'^(?P<pk>\d+)/widgets/$', views.CompetitionWidgetsView.as_view(), name='widgets'),
    url(r'^submission_widget/(?P<pk>\d+)/$', views.CompetitionSubmissionWidgetView.as_view(), name='submission_widget'),
    url(r'^leaderboard_widget/(?P<pk>\d+)/$', views.CompetitionLeaderboardWidgetView.as_view(), name='leaderboard_widget'),
]
