# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-13 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_forum_competition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='competition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum', to='web.Competition'),
        ),
    ]
