#!/usr/bin/ruby

if ARGV.size != 2
  puts "Usage: #{$0} <input directory with csv files> <output directories with ARFF files>"
  exit 1
end

input, output = ARGV

runjava = File.dirname($0) + '/runjava'

source = input + '/data.csv'
dest = output + '/data.arff'
puts "Converting #{source} => #{dest}"
system "#{runjava} weka.core.converters.CSVLoader '#{source}' > '#{dest}'" or exit 1
