# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-10-03 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cluser',
            options={},
        ),
        migrations.AddField(
            model_name='cluser',
            name='chahub_data_hash',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cluser',
            name='chahub_needs_retry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cluser',
            name='chahub_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
