# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-12-15 00:21
from __future__ import unicode_literals

import apps.authenz.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cluser',
            managers=[
                ('objects', apps.authenz.models.CodalabUserManager()),
            ],
        ),
    ]
