# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', models.TextField(blank=True, null=True)),
                ('threshold', models.PositiveIntegerField(blank=True, default=25, null=True)),
            ],
        ),
    ]
