# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-04-18 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthsettings',
            name='congestion_threshold',
            field=models.PositiveIntegerField(blank=True, default=100, null=True),
        ),
    ]
