# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-22 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageDataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bucket_name', models.CharField(max_length=255)),
                ('total_use', models.BigIntegerField(default=0)),
                ('competition_use', models.BigIntegerField(default=0)),
                ('submission_use', models.BigIntegerField(default=0)),
                ('dataset_use', models.BigIntegerField(default=0)),
                ('bundle_use', models.BigIntegerField(default=0)),
                ('dumps_use', models.BigIntegerField(default=0)),
            ],
        ),
    ]
