# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-06-13 05:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_healthsettings_congestion_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_predicting', models.BooleanField(default=False)),
                ('is_scoring', models.BooleanField(default=False)),
                ('start', models.TimeField(blank=True, null=True)),
                ('end', models.TimeField(blank=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='web.CompetitionSubmission')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField()),
                ('ip', models.TextField(max_length=24)),
                ('cpu_count', models.PositiveIntegerField()),
                ('mem_mb', models.PositiveIntegerField()),
                ('harddrive_gb', models.PositiveIntegerField()),
                ('gpus', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='taskmetadata',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='health.Worker'),
        ),
    ]
