# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-08-21 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0002_auto_20180519_0502'),
        ('web', '0014_auto_20190703_2144'),
        ('health', '0002_healthsettings_congestion_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_predicting', models.BooleanField(default=True)),
                ('is_scoring', models.BooleanField(default=False)),
                ('queued', models.DateTimeField(default=django.utils.timezone.now)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='web.CompetitionSubmission')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField()),
                ('ip', models.TextField(blank=True, max_length=24, null=True)),
                ('cpu_count', models.PositiveIntegerField(blank=True, null=True)),
                ('mem_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('harddrive_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('gpus', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('last_keep_alive', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='queues.Queue')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerStateChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up', models.BooleanField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Worker')),
            ],
        ),
        migrations.AddField(
            model_name='taskmetadata',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='health.Worker'),
        ),
    ]
