# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-12 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_storagedatapoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionStorageDataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('creator', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('submissions', models.BigIntegerField(default=0)),
                ('datasets', models.BigIntegerField(default=0)),
                ('dumps', models.BigIntegerField(default=0)),
                ('bundle', models.BigIntegerField(default=0)),
                ('total', models.BigIntegerField(default=0)),
            ],
        ),
    ]
