# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-13 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_competitionstoragedatapoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionstoragedatapoint',
            name='id',
        ),
        migrations.AlterField(
            model_name='competitionstoragedatapoint',
            name='competition_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
