# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-06-18 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_auto_20190613_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmetadata',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskmetadata',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
