# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-10-13 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_auto_20190821_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmetadata',
            name='failed_to_complete',
            field=models.BooleanField(default=False),
        ),
    ]
