# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-06-27 05:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0002_auto_20180519_0502'),
        ('health', '0004_auto_20190618_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='queue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='queues.Queue'),
        ),
    ]
