# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-28 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_auto_20220713_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bucket_name', models.CharField(max_length=255)),
                ('total_use', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StorageUsageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bucket_name', models.CharField(max_length=255)),
                ('at_date', models.DateTimeField()),
                ('usage', models.BigIntegerField(default=0)),
            ],
        ),
    ]
