#!/bin/bash
THIS_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

PROJECT_DIR=$(readlink -f ../codalab)
ROOT_DIR=$(readlink -f ..)
REQ_DIR=$PROJECT_DIR/requirements/

VENV_DIR=$ROOT_DIR/venv
WHEEL_DIR=$ROOT_DIR/wheel_packages
PIP_CMD="pip wheel --wheel-dir=$ROOT_DIR/wheel_packages"

pushd `pwd` > /dev/null
cd $ROOT_DIR
GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
GIT_HASH=$(git rev-parse  HEAD)
popd > /dev/null


REQS=$1
CONFIG=$2
OUTFILE=$3

if [ -z "$REQS" ] || [ -z "$CONFIG" ] || [ -z "$OUTFILE" ]; then echo "Need to specify REQS and CONFIG an OUTFILE" && exit 1 ; fi

virtualenv $VENV_DIR && source $VENV_DIR/bin/activate
source $THIS_DIR/base_pip_requirements

# remove possible stale entries
if [ -d "$WHEEL_DIR" ] ; then
 rm -rf "$WHEEL_DIR"/* 
fi

$PIP_CMD -r $REQ_DIR/$REQS
$PIP_CMD -U --force-reinstall $CONFIG

deactivate
# Remove VEVN dir before makeing tarball
if [ -d "$VENV_DIR" ] ; then
 rm -rf "$VENV_DIR"/* 
fi

tar --exclude=.git\* --exclude=\#\* --exclude=\*~  -C $(dirname "$ROOT_DIR") -cvf - $(basename "$ROOT_DIR") | gzip -9 -c > $OUTFILE





