# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-16 18:50
from __future__ import unicode_literals

import apps.web.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import mptt.fields
import s3direct.fields
import storages.backends.s3boto3


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('queues', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chahub_timestamp', models.DateTimeField(blank=True, null=True)),
                ('chahub_data_hash', models.TextField(blank=True, null=True)),
                ('chahub_needs_retry', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('url_redirect', models.URLField(blank=True, help_text='(NOTE: You should not have Registration Required above checked if using URL redirection, because upon redirect participants will not be approved and unable to participate.)', null=True, verbose_name='URL Redirect')),
                ('image', models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='tthomas-codalab-public'), upload_to=apps.web.models._uuidify('logos'), verbose_name='Logo')),
                ('image_url_base', models.CharField(max_length=255)),
                ('has_registration', models.BooleanField(default=False, verbose_name='Registration Required')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start Date (UTC)')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date (UTC)')),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=False, verbose_name='Publicly Available')),
                ('last_phase_migration', models.PositiveIntegerField(default=1)),
                ('is_migrating', models.BooleanField(default=False)),
                ('force_submission_to_leaderboard', models.BooleanField(default=False)),
                ('disallow_leaderboard_modifying', models.BooleanField(default=False)),
                ('secret_key', django_extensions.db.fields.UUIDField(blank=True, editable=False)),
                ('enable_medical_image_viewer', models.BooleanField(default=False)),
                ('enable_detailed_results', models.BooleanField(default=False)),
                ('original_yaml_file', models.TextField(blank=True, default='', null=True)),
                ('show_datasets_from_yaml', models.BooleanField(default=True)),
                ('reward', models.PositiveIntegerField(blank=True, null=True)),
                ('is_migrating_delayed', models.BooleanField(default=False)),
                ('allow_teams', models.BooleanField(default=False)),
                ('enable_per_submission_metadata', models.BooleanField(default=False, help_text='(Team name, Method name, Method description, etc.)')),
                ('allow_public_submissions', models.BooleanField(default=False, verbose_name='Allow sharing of public submissions')),
                ('enable_forum', models.BooleanField(default=False)),
                ('anonymous_leaderboard', models.BooleanField(default=False)),
                ('enable_teams', models.BooleanField(default=False, verbose_name='Enable Competition level teams')),
                ('require_team_approval', models.BooleanField(default=True, verbose_name='Organizers need to approve the new teams')),
                ('hide_top_three', models.BooleanField(default=False, verbose_name='Hide Top Three Leaderboard')),
                ('hide_chart', models.BooleanField(default=False, verbose_name='Hide Chart')),
                ('allow_organizer_teams', models.BooleanField(default=False, verbose_name='Allow Organizer Teams')),
                ('competition_docker_image', models.CharField(blank=True, default='', max_length=128)),
                ('deleted', models.BooleanField(default=False)),
                ('admins', models.ManyToManyField(blank=True, null=True, related_name='competition_admins', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitioninfo_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitioninfo_modified_by', to=settings.AUTH_USER_MODEL)),
                ('queue', models.ForeignKey(blank=True, help_text="(don't change this unless you have a reason to, default/empty is fine)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions', to='queues.Queue')),
                ('teams', models.ManyToManyField(blank=True, null=True, related_name='competition_teams', to='teams.Team')),
            ],
            options={
                'ordering': ['end_date'],
                'permissions': (('is_owner', 'Owner'), ('can_edit', 'Edit')),
            },
        ),
        migrations.CreateModel(
            name='CompetitionDefBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_bundle', models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='tthomas-codalab-private'), upload_to=apps.web.models._uuidify('competition-bundles'))),
                ('s3_config_bundle', s3direct.fields.S3DirectField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionDump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Starting', max_length=64)),
                ('data_file', models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='tthomas-codalab-private'), upload_to=apps.web.models._uuidify('competition_dump'), verbose_name='Data file')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dumps', to='web.Competition')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='web.Competition')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('phasenumber', models.PositiveIntegerField(verbose_name='Number')),
                ('label', models.CharField(blank=True, max_length=50, verbose_name='Name')),
                ('start_date', models.DateTimeField(verbose_name='Start Date (UTC)')),
                ('max_submissions', models.PositiveIntegerField(default=100, verbose_name='Maximum Submissions (per User)')),
                ('max_submissions_per_day', models.PositiveIntegerField(default=999, verbose_name='Max Submissions (per User) per day')),
                ('is_scoring_only', models.BooleanField(default=True, verbose_name='Results Scoring Only')),
                ('scoring_program', models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='tthomas-codalab-private'), upload_to=apps.web.models._uuidify('phase_scoring_program_file'), verbose_name='Scoring Program')),
                ('reference_data', models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='tthomas-codalab-private'), upload_to=apps.web.models._uuidify('phase_reference_data_file'), verbose_name='Reference Data')),
                ('input_data', models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='tthomas-codalab-private'), upload_to=apps.web.models._uuidify('phase_input_data_file'), verbose_name='Input Data')),
                ('leaderboard_management_mode', models.CharField(default='default', max_length=50, verbose_name='Leaderboard Mode')),
                ('force_best_submission_to_leaderboard', models.BooleanField(default=False, verbose_name='If submission beats old score, put submission on leaderboard')),
                ('auto_migration', models.BooleanField(default=False)),
                ('is_migrated', models.BooleanField(default=False)),
                ('execution_time_limit', models.PositiveIntegerField(default=300, verbose_name='Execution time limit (in seconds)')),
                ('color', models.CharField(blank=True, choices=[('white', 'White'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple')], max_length=24, null=True)),
                ('phase_never_ends', models.BooleanField(default=False)),
                ('scoring_program_docker_image', models.CharField(blank=True, default='', max_length=128)),
                ('default_docker_image', models.CharField(blank=True, default='', max_length=128)),
                ('disable_custom_docker_image', models.BooleanField(default=True)),
                ('starting_kit', models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='tthomas-codalab-private'), upload_to=apps.web.models._uuidify('starting_kit'), verbose_name='Starting Kit')),
                ('public_data', models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='tthomas-codalab-private'), upload_to=apps.web.models._uuidify('public_data'), verbose_name='Public Data')),
                ('ingestion_program', models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='tthomas-codalab-private'), upload_to=apps.web.models._uuidify('ingestion_program'))),
                ('ingestion_program_docker_image', models.CharField(blank=True, default='', max_length=128)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='web.Competition')),
            ],
            options={
                'ordering': ['phasenumber'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chahub_timestamp', models.DateTimeField(blank=True, null=True)),
                ('chahub_data_hash', models.TextField(blank=True, null=True)),
                ('chahub_needs_retry', models.BooleanField(default=False)),
                ('secret', models.CharField(blank=True, default='', max_length=128)),
                ('docker_image', models.CharField(blank=True, default='', max_length=128)),
                ('file', models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='tthomas-codalab-private'), upload_to=apps.web.models._uuidify('submission_file_name'))),
                ('s3_file', s3direct.fields.S3DirectField(blank=True, null=True)),
                ('file_url_base', models.CharField(blank=True, max_length=2000)),
                ('readable_filename', models.TextField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('inputfile', models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='tthomas-codalab-private'), upload_to=apps.web.models._uuidify('submission_inputfile'))),
                ('runfile', models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='tthomas-codalab-private'), upload_to=apps.web.models._uuidify('submission_runfile'))),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_key', models.TextField(blank=True, default='')),
                ('status_details', models.CharField(blank=True, max_length=100, null=True)),
                ('submission_number', models.PositiveIntegerField(default=0)),
                ('output_file', models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='tthomas-codalab-private'), upload_to=apps.web.models._uuidify('submission_output'))),
                ('private_output_file', models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='tthomas-codalab-private'), upload_to=apps.web.models._uuidify('submission_private_output'))),
                ('stdout_file', models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='tthomas-codalab-private'), upload_to=apps.web.models._uuidify('submission_stdout'))),
                ('stderr_file', models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='tthomas-codalab-private'), upload_to=apps.web.models._uuidify('submission_stderr'))),
                ('history_file', models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='tthomas-codalab-private'), upload_to=apps.web.models._uuidify('submission_history'))),
                ('scores_file', models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='tthomas-codalab-private'), upload_to=apps.web.models._uuidify('submission_scores'))),
                ('coopetition_file', models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='tthomas-codalab-private'), upload_to=apps.web.models._uuidify('submission_coopetition'))),
                ('detailed_results_file', models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='tthomas-codalab-private'), upload_to=apps.web.models._uuidify('submission_detailed_results'))),
                ('prediction_runfile', models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='tthomas-codalab-private'), upload_to=apps.web.models._uuidify('submission_prediction_runfile'))),
                ('prediction_output_file', models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='tthomas-codalab-private'), upload_to=apps.web.models._uuidify('submission_prediction_output'))),
                ('exception_details', models.TextField(blank=True, null=True)),
                ('prediction_stdout_file', models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='tthomas-codalab-private'), upload_to=apps.web.models._uuidify('predict_submission_stdout'))),
                ('prediction_stderr_file', models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='tthomas-codalab-private'), upload_to=apps.web.models._uuidify('predict_submission_stderr'))),
                ('ingestion_program_stdout_file', models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='tthomas-codalab-private'), upload_to=apps.web.models._uuidify('predict_submission_stdout'))),
                ('ingestion_program_stderr_file', models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='tthomas-codalab-private'), upload_to=apps.web.models._uuidify('predict_submission_stderr'))),
                ('method_name', models.CharField(blank=True, max_length=20, null=True)),
                ('method_description', models.TextField(blank=True, null=True)),
                ('project_url', models.URLField(blank=True, null=True)),
                ('publication_url', models.URLField(blank=True, null=True)),
                ('bibtex', models.TextField(blank=True, null=True)),
                ('organization_or_affiliation', models.CharField(blank=True, max_length=255, null=True)),
                ('team_name', models.CharField(blank=True, max_length=64, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('when_made_public', models.DateTimeField(blank=True, null=True)),
                ('when_unmade_public', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('dislike_count', models.IntegerField(default=0)),
                ('is_migrated', models.BooleanField(default=False)),
                ('queue_name', models.TextField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='web.CompetitionParticipant')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='web.CompetitionPhase')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionSubmissionMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_predict', models.BooleanField(default=False)),
                ('is_scoring', models.BooleanField(default=False)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('processes_running_in_temp_dir', models.TextField(blank=True, null=True)),
                ('ingestion_program_duration', models.TextField(blank=True, null=True)),
                ('beginning_virtual_memory_usage', models.TextField(blank=True, null=True)),
                ('beginning_swap_memory_usage', models.TextField(blank=True, null=True)),
                ('beginning_cpu_usage', models.TextField(blank=True, null=True)),
                ('end_virtual_memory_usage', models.TextField(blank=True, null=True)),
                ('end_swap_memory_usage', models.TextField(blank=True, null=True)),
                ('end_cpu_usage', models.TextField(blank=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadatas', to='web.CompetitionSubmission')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionSubmissionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('codename', models.SlugField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('codename', models.SlugField(max_length=100, unique=True)),
                ('is_menu', models.BooleanField(default=True)),
                ('content_limit', models.PositiveIntegerField(default=1)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='web.ContentCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentVisibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('codename', models.SlugField(max_length=20, unique=True)),
                ('classname', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('number', models.PositiveIntegerField(default=1)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='DefaultContentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('codename', models.SlugField(max_length=100, unique=True)),
                ('rank', models.IntegerField(default=0)),
                ('required', models.BooleanField(default=False)),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ContentCategory')),
                ('initial_visibility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ContentVisibility')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source_url', models.URLField()),
                ('source_address_info', models.CharField(blank=True, max_length=200)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalFileSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('codename', models.SlugField(unique=True)),
                ('service_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalFileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('codename', models.SlugField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizerDataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.TextField(default='')),
                ('type', models.CharField(choices=[('Reference Data', 'Reference Data'), ('Scoring Program', 'Scoring Program'), ('Input Data', 'Input Data'), ('Ingestion Program', 'Ingestion Program'), ('Starting Kit', 'Starting Kit'), ('Public Data', 'Public Data'), ('None', 'None')], default='None', max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('data_file', models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='tthomas-codalab-private'), upload_to=apps.web.models._uuidify('dataset_data_file'), verbose_name='Data file')),
                ('key', django_extensions.db.fields.UUIDField(blank=True, editable=False)),
                ('sub_data_files', models.ManyToManyField(blank=True, null=True, to='web.OrganizerDataSet', verbose_name='Bundle of data files')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.SlugField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('label', models.CharField(max_length=100, verbose_name='Title')),
                ('rank', models.IntegerField(default=0, verbose_name='Order')),
                ('visibility', models.BooleanField(default=True, verbose_name='Visible')),
                ('markup', models.TextField(blank=True)),
                ('html', models.TextField(blank=True, verbose_name='Content')),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ContentCategory')),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='web.Competition')),
            ],
            options={
                'ordering': ['category', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='PageContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('codename', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PhaseLeaderBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='board', to='web.CompetitionPhase')),
            ],
        ),
        migrations.CreateModel(
            name='PhaseLeaderBoardEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='web.PhaseLeaderBoard')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entry_result', to='web.CompetitionSubmission')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionComputedScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('Max', 'Max'), ('Avg', 'Average')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionComputedScoreField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='web.SubmissionComputedScore')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionResultGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=50)),
                ('ordering', models.PositiveIntegerField(default=1)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Competition')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionResultGroupPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.SubmissionResultGroup')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.CompetitionPhase')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=10, max_digits=20)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='web.CompetitionSubmission')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionScoreDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=50)),
                ('label', models.CharField(max_length=50)),
                ('sorting', models.SlugField(choices=[('asc', 'Ascending'), ('desc', 'Descending')], default='asc', max_length=20)),
                ('numeric_format', models.CharField(blank=True, max_length=20, null=True)),
                ('show_rank', models.BooleanField(default=False)),
                ('selection_default', models.IntegerField(default=0)),
                ('computed', models.BooleanField(default=False)),
                ('ordering', models.PositiveIntegerField(default=1)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Competition')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionScoreDefGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.SubmissionResultGroup')),
                ('scoredef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.SubmissionScoreDef')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionScoreSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=50)),
                ('ordering', models.PositiveIntegerField(default=1)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Competition')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='web.SubmissionScoreSet')),
                ('scoredef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.SubmissionScoreDef')),
            ],
        ),
        migrations.AddField(
            model_name='submissionscoredef',
            name='groups',
            field=models.ManyToManyField(through='web.SubmissionScoreDefGroup', to='web.SubmissionResultGroup'),
        ),
        migrations.AddField(
            model_name='submissionscore',
            name='scoredef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.SubmissionScoreDef'),
        ),
        migrations.AddField(
            model_name='submissionresultgroup',
            name='phases',
            field=models.ManyToManyField(through='web.SubmissionResultGroupPhase', to='web.CompetitionPhase'),
        ),
        migrations.AddField(
            model_name='submissioncomputedscorefield',
            name='scoredef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.SubmissionScoreDef'),
        ),
        migrations.AddField(
            model_name='submissioncomputedscore',
            name='scoredef',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='computed_score', to='web.SubmissionScoreDef'),
        ),
        migrations.AddField(
            model_name='page',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='web.PageContainer', verbose_name='Page Container'),
        ),
        migrations.AddField(
            model_name='page',
            name='defaults',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.DefaultContentItem'),
        ),
        migrations.AddField(
            model_name='externalfile',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ExternalFileType'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='datafile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ExternalFile'),
        ),
        migrations.AddField(
            model_name='contentcategory',
            name='visibility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ContentVisibility'),
        ),
        migrations.AddField(
            model_name='competitionsubmission',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.CompetitionSubmissionStatus'),
        ),
        migrations.AddField(
            model_name='competitionsubmission',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='teams.Team'),
        ),
        migrations.AddField(
            model_name='competitionphase',
            name='datasets',
            field=models.ManyToManyField(blank=True, related_name='phase', to='web.Dataset'),
        ),
        migrations.AddField(
            model_name='competitionphase',
            name='ingestion_program_organizer_dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_program_organizer_dataset', to='web.OrganizerDataSet'),
        ),
        migrations.AddField(
            model_name='competitionphase',
            name='input_data_organizer_dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='input_data_organizer_dataset', to='web.OrganizerDataSet', verbose_name='Input Data'),
        ),
        migrations.AddField(
            model_name='competitionphase',
            name='public_data_organizer_dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_data_organizer_dataset', to='web.OrganizerDataSet', verbose_name='Public Data'),
        ),
        migrations.AddField(
            model_name='competitionphase',
            name='reference_data_organizer_dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_data_organizer_dataset', to='web.OrganizerDataSet', verbose_name='Reference Data'),
        ),
        migrations.AddField(
            model_name='competitionphase',
            name='scoring_program_organizer_dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scoring_program_organizer_dataset', to='web.OrganizerDataSet', verbose_name='Scoring Program'),
        ),
        migrations.AddField(
            model_name='competitionphase',
            name='starting_kit_organizer_dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starting_kit_organizer_dataset', to='web.OrganizerDataSet', verbose_name='Starting Kit'),
        ),
        migrations.AddField(
            model_name='competitionparticipant',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ParticipantStatus'),
        ),
        migrations.AddField(
            model_name='competitionparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='submissionscoreset',
            unique_together=set([('key', 'competition')]),
        ),
        migrations.AlterUniqueTogether(
            name='submissionscoredefgroup',
            unique_together=set([('scoredef', 'group')]),
        ),
        migrations.AlterUniqueTogether(
            name='submissionscoredef',
            unique_together=set([('key', 'competition')]),
        ),
        migrations.AlterUniqueTogether(
            name='submissionscore',
            unique_together=set([('result', 'scoredef')]),
        ),
        migrations.AlterUniqueTogether(
            name='submissionresultgroupphase',
            unique_together=set([('group', 'phase')]),
        ),
        migrations.AlterUniqueTogether(
            name='phaseleaderboardentry',
            unique_together=set([('board', 'result')]),
        ),
        migrations.AlterUniqueTogether(
            name='pagecontainer',
            unique_together=set([('object_id', 'content_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set([('label', 'category', 'container')]),
        ),
        migrations.AlterUniqueTogether(
            name='competitionsubmission',
            unique_together=set([('submission_number', 'phase', 'participant')]),
        ),
        migrations.AlterUniqueTogether(
            name='competitionparticipant',
            unique_together=set([('user', 'competition')]),
        ),
    ]
