# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import s3direct.fields
import storages.backends.s3boto
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='secret_key',
            field=models.UUIDField(default=uuid.UUID('a93498d4-b3b2-4312-a5b0-4efc05ea60b6')),
        ),
        migrations.AlterField(
            model_name='competitiondefbundle',
            name='config_bundle',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3boto.S3BotoStorage(bucket_name=b'codalab-eric-local-private'), upload_to=b'competition-bundles'),
        ),
        migrations.AlterField(
            model_name='competitiondefbundle',
            name='s3_config_bundle',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competitionsubmission',
            name='s3_file',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
    ]
