# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-19 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20180519_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='secret_key',
            field=models.UUIDField(default=uuid.UUID('5525d429-4e75-4ea8-a276-eb630441c3d8')),
        ),
    ]
