# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-17 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20180519_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionsubmission',
            name='task_id',
            field=models.CharField(default=b'', max_length=64),
        ),
        migrations.AlterField(
            model_name='competition',
            name='secret_key',
            field=models.UUIDField(default=uuid.UUID('7f8df7df-df66-4b90-8217-ad09d9ed4574')),
        ),
    ]
