# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-20 18:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20220328_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='upper_bound_max_submission_size',
            field=models.PositiveIntegerField(default=300, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Upper bound max submission size in megabytes'),
        ),
    ]
