# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-22 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20180519_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionphase',
            name='is_parallel_parent',
            field=models.BooleanField(default=False, help_text=b'This phase itself does no processing, it is just a placeholder for subphases to do their magic'),
        ),
        migrations.AddField(
            model_name='competitionphase',
            name='parent',
            field=models.ForeignKey(blank=True, help_text=b"Parent phase MUST be a 'parallel parent' type phase", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_phases', to='web.CompetitionPhase'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='secret_key',
            field=models.UUIDField(default=uuid.UUID('d2318f98-0f2f-4a72-9784-922a0b73ec69')),
        ),
    ]
