# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-03 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20180522_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionsubmission',
            name='parent_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_submissions', to='web.CompetitionSubmission'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='secret_key',
            field=models.UUIDField(default=uuid.UUID('c8e22646-cde0-4d91-bfbc-64dd46c20df7')),
        ),
        migrations.AlterField(
            model_name='competitionphase',
            name='parent',
            field=models.ForeignKey(blank=True, help_text=b"Parent phase MUST be a 'parallel parent' type phase. If you can't select the parent phase here, set it to be a 'parallel parent' phase and save this form, then it should appear in the dropdown", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_phases', to='web.CompetitionPhase'),
        ),
    ]
