# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-28 04:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20180817_2107'),
        ('web', '0007_auto_20180603_2304'),
    ]

    operations = [
    ]
