# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-06 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20180603_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionsubmission',
            name='task_id',
            field=models.CharField(default=b'', max_length=64),
        ),
        migrations.AlterField(
            model_name='competition',
            name='secret_key',
            field=models.UUIDField(default=uuid.UUID('bb0c5ec8-fcd5-45a8-9da1-40e4fc98bd11')),
        ),
    ]
