# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-06 22:22
from __future__ import unicode_literals

from django.db import migrations


def update_content_categories(apps, schema_editor):
    ContentCategory = apps.get_model('web', 'ContentCategory')

    # Update or create example
    # obj, created = Person.objects.update_or_create(
    #     first_name='John',
    #     last_name='Lennon',
    #     defaults=updated_values
    # )

    ContentCategory.update_or_create(
        name="Home",
        defaults={
            "name": "New Home"
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20180906_2222'),
    ]

    operations = [
        migrations.RunPython(update_content_categories)
    ]
