# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-09 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20180906_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionphase',
            name='hidden_columns',
            field=models.CharField(blank=True, default=b'', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='secret_key',
            field=models.UUIDField(default=uuid.UUID('d87d4c9c-19a5-4699-abbe-97c3816fb4e7')),
        ),
    ]
