# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-14 00:17
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20181009_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='submit_to_all_phases',
            field=models.BooleanField(default=False, verbose_name=b'Submit to all phases'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='secret_key',
            field=models.UUIDField(default=uuid.UUID('ac881e9d-d2d3-4510-9a1b-61a9b9784249')),
        ),
    ]
