# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-05-07 19:57
from __future__ import unicode_literals

import apps.web.models
import apps.web.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20190315_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionphase',
            name='max_execution_time_limit',
            field=models.PositiveIntegerField(default=30000, verbose_name=b'Max Total Execution time limit (in seconds)'),
        ),
    ]
