# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-07-03 21:44
from __future__ import unicode_literals

import apps.web.models
import apps.web.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20190507_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='image',
            field=models.FileField(blank=True, null=True, storage=apps.web.storage.CodalabGoogleCloudStorage(bucket_name=b'codalab-gcs-public'), upload_to=apps.web.models._uuidify(b'logos'), verbose_name=b'Logo'),
        ),
        migrations.AlterField(
            model_name='competitiondefbundle',
            name='config_bundle',
            field=models.FileField(blank=True, null=True, storage=apps.web.storage.CodalabGoogleCloudStorage(bucket_name=b'codalab-gcs-private'), upload_to=apps.web.models._uuidify(b'competition-bundles')),
        ),
        migrations.AlterField(
            model_name='competitiondump',
            name='data_file',
            field=models.FileField(blank=True, null=True, storage=apps.web.storage.CodalabGoogleCloudStorage(bucket_name=b'codalab-gcs-private'), upload_to=apps.web.models._uuidify(b'competition_dump'), verbose_name=b'Data file'),
        ),
        migrations.AlterField(
            model_name='competitionphase',
            name='ingestion_program',
            field=models.FileField(blank=True, null=True, storage=apps.web.storage.CodalabGoogleCloudStorage(bucket_name=b'codalab-gcs-private'), upload_to=apps.web.models._uuidify(b'ingestion_program')),
        ),
        migrations.AlterField(
            model_name='competitionphase',
            name='input_data',
            field=models.FileField(blank=True, null=True, storage=apps.web.storage.CodalabGoogleCloudStorage(bucket_name=b'codalab-gcs-private'), upload_to=apps.web.models._uuidify(b'phase_input_data_file'), verbose_name=b'Input Data'),
        ),
        migrations.AlterField(
            model_name='competitionphase',
            name='max_execution_time_limit',
            field=models.PositiveIntegerField(default=30000, verbose_name=b'Max Execution time limit for 24 hours (in seconds)'),
        ),
        migrations.AlterField(
            model_name='competitionphase',
            name='public_data',
            field=models.FileField(blank=True, null=True, storage=apps.web.storage.CodalabGoogleCloudStorage(bucket_name=b'codalab-gcs-private'), upload_to=apps.web.models._uuidify(b'public_data'), verbose_name=b'Public Data'),
        ),
        migrations.AlterField(
            model_name='competitionphase',
            name='reference_data',
            field=models.FileField(blank=True, null=True, storage=apps.web.storage.CodalabGoogleCloudStorage(bucket_name=b'codalab-gcs-private'), upload_to=apps.web.models._uuidify(b'phase_reference_data_file'), verbose_name=b'Reference Data'),
        ),
        migrations.AlterField(
            model_name='competitionphase',
            name='scoring_program',
            field=models.FileField(blank=True, null=True, storage=apps.web.storage.CodalabGoogleCloudStorage(bucket_name=b'codalab-gcs-private'), upload_to=apps.web.models._uuidify(b'phase_scoring_program_file'), verbose_name=b'Scoring Program'),
        ),
        migrations.AlterField(
            model_name='competitionphase',
            name='starting_kit',
            field=models.FileField(blank=True, null=True, storage=apps.web.storage.CodalabGoogleCloudStorage(bucket_name=b'codalab-gcs-private'), upload_to=apps.web.models._uuidify(b'starting_kit'), verbose_name=b'Starting Kit'),
        ),
        migrations.AlterField(
            model_name='competitionsubmission',
            name='coopetition_file',
            field=models.FileField(blank=True, null=True, storage=apps.web.storage.CodalabGoogleCloudStorage(bucket_name=b'codalab-gcs-private'), upload_to=apps.web.models._uuidify(b'submission_coopetition')),
        ),
        migrations.AlterField(
            model_name='competitionsubmission',
            name='detailed_results_file',
            field=models.FileField(blank=True, null=True, storage=apps.web.storage.CodalabGoogleCloudStorage(bucket_name=b'codalab-gcs-private'), upload_to=apps.web.models._uuidify(b'submission_detailed_results')),
        ),
        migrations.AlterField(
            model_name='competitionsubmission',
            name='file',
            field=models.FileField(blank=True, null=True, storage=apps.web.storage.CodalabGoogleCloudStorage(bucket_name=b'codalab-gcs-private'), upload_to=b''),
        ),
        migrations.AlterField(
            model_name='competitionsubmission',
            name='history_file',
            field=models.FileField(blank=True, null=True, storage=apps.web.storage.CodalabGoogleCloudStorage(bucket_name=b'codalab-gcs-private'), upload_to=apps.web.models._uuidify(b'submission_history')),
        ),
        migrations.AlterField(
            model_name='competitionsubmission',
            name='ingestion_program_stderr_file',
            field=models.FileField(blank=True, null=True, storage=apps.web.storage.CodalabGoogleCloudStorage(bucket_name=b'codalab-gcs-private'), upload_to=apps.web.models._uuidify(b'predict_submission_stderr')),
        ),
        migrations.AlterField(
            model_name='competitionsubmission',
            name='ingestion_program_stdout_file',
            field=models.FileField(blank=True, null=True, storage=apps.web.storage.CodalabGoogleCloudStorage(bucket_name=b'codalab-gcs-private'), upload_to=apps.web.models._uuidify(b'predict_submission_stdout')),
        ),
        migrations.AlterField(
            model_name='competitionsubmission',
            name='inputfile',
            field=models.FileField(blank=True, null=True, storage=apps.web.storage.CodalabGoogleCloudStorage(bucket_name=b'codalab-gcs-private'), upload_to=apps.web.models._uuidify(b'submission_inputfile')),
        ),
        migrations.AlterField(
            model_name='competitionsubmission',
            name='output_file',
            field=models.FileField(blank=True, null=True, storage=apps.web.storage.CodalabGoogleCloudStorage(bucket_name=b'codalab-gcs-private'), upload_to=apps.web.models._uuidify(b'submission_output')),
        ),
        migrations.AlterField(
            model_name='competitionsubmission',
            name='prediction_output_file',
            field=models.FileField(blank=True, null=True, storage=apps.web.storage.CodalabGoogleCloudStorage(bucket_name=b'codalab-gcs-private'), upload_to=apps.web.models._uuidify(b'submission_prediction_output')),
        ),
        migrations.AlterField(
            model_name='competitionsubmission',
            name='prediction_runfile',
            field=models.FileField(blank=True, null=True, storage=apps.web.storage.CodalabGoogleCloudStorage(bucket_name=b'codalab-gcs-private'), upload_to=apps.web.models._uuidify(b'submission_prediction_runfile')),
        ),
        migrations.AlterField(
            model_name='competitionsubmission',
            name='prediction_stderr_file',
            field=models.FileField(blank=True, null=True, storage=apps.web.storage.CodalabGoogleCloudStorage(bucket_name=b'codalab-gcs-private'), upload_to=apps.web.models._uuidify(b'predict_submission_stderr')),
        ),
        migrations.AlterField(
            model_name='competitionsubmission',
            name='prediction_stdout_file',
            field=models.FileField(blank=True, null=True, storage=apps.web.storage.CodalabGoogleCloudStorage(bucket_name=b'codalab-gcs-private'), upload_to=apps.web.models._uuidify(b'predict_submission_stdout')),
        ),
        migrations.AlterField(
            model_name='competitionsubmission',
            name='private_output_file',
            field=models.FileField(blank=True, null=True, storage=apps.web.storage.CodalabGoogleCloudStorage(bucket_name=b'codalab-gcs-private'), upload_to=apps.web.models._uuidify(b'submission_private_output')),
        ),
        migrations.AlterField(
            model_name='competitionsubmission',
            name='runfile',
            field=models.FileField(blank=True, null=True, storage=apps.web.storage.CodalabGoogleCloudStorage(bucket_name=b'codalab-gcs-private'), upload_to=apps.web.models._uuidify(b'submission_runfile')),
        ),
        migrations.AlterField(
            model_name='competitionsubmission',
            name='scores_file',
            field=models.FileField(blank=True, null=True, storage=apps.web.storage.CodalabGoogleCloudStorage(bucket_name=b'codalab-gcs-private'), upload_to=apps.web.models._uuidify(b'submission_scores')),
        ),
        migrations.AlterField(
            model_name='competitionsubmission',
            name='stderr_file',
            field=models.FileField(blank=True, null=True, storage=apps.web.storage.CodalabGoogleCloudStorage(bucket_name=b'codalab-gcs-private'), upload_to=apps.web.models._uuidify(b'submission_stderr')),
        ),
        migrations.AlterField(
            model_name='competitionsubmission',
            name='stdout_file',
            field=models.FileField(blank=True, null=True, storage=apps.web.storage.CodalabGoogleCloudStorage(bucket_name=b'codalab-gcs-private'), upload_to=apps.web.models._uuidify(b'submission_stdout')),
        ),
        migrations.AlterField(
            model_name='organizerdataset',
            name='data_file',
            field=models.FileField(blank=True, null=True, storage=apps.web.storage.CodalabGoogleCloudStorage(bucket_name=b'codalab-gcs-private'), upload_to=apps.web.models._uuidify(b'dataset_data_file'), verbose_name=b'Data file'),
        ),
    ]
