#!/bin/bash

## This will eventually be a bit more configurable

THIS_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
pushd `pwd` 2>&1 > /dev/null
cd $THIS_DIR

U=$1

if [[ $U =~ [a-zA-Z0-9][\-\_a-zA-Z0-9]+[a-zA-Z0-9] ]] ; then
  if [ $(id -u $U) -lt 1000 ]; then echo "Invalid user specified"; exit 1; fi
  if ! id -u "$U" 2>&1 > /dev/null; then
    echo "User will be added."
    useradd -m -s /bin/bash $U
    passwd $U
  fi
else
  echo "User not specified or username has bad characters"
  exit 1
fi

echo "Installing codalab dependency meta-package..."
apt-get -y remove codalab-reqs
apt-get -y autoremove && \
## gdebi will install a .deb and all the dependencies
apt-get install -y gdebi-core && \
#dpkg -i *.deb 2>&1 /dev/null && \
gdebi -q -n *.deb && \
#echo "Installing dependencies..." && \
#apt-get -f install > /dev/null && \
echo "Updaing some group permissions..." && \
chgrp -R www-data /var/log/nginx /var/lib/nginx && \
chmod -R g+rw   /var/log/nginx /var/lib/nginx && \
usermod -a -G www-data $U
rc=$?
if [[ $rc != 0 ]] ; then
   echo "*** There was an error setting up the server."
   exit $rc
fi
popd > /dev/null
