# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-28 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0002_configuration_only_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='disable_all_submissions',
            field=models.BooleanField(default=False, verbose_name='Disable all sumbissions'),
        ),
    ]
