# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-28 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20200716_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Competition'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='competition1234-public'), upload_to='team_logo', verbose_name='Logo'),
        ),
    ]
