# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-04 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import storages.backends.gcloud


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20180403_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.FileField(blank=True, null=True, storage=storages.backends.gcloud.GoogleCloudStorage(bucket_name=None), upload_to=b'team_logo', verbose_name=b'Logo'),
        ),
    ]
