# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-19 05:02
from __future__ import unicode_literals

import apps.web.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20180404_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.FileField(blank=True, null=True, storage=apps.web.storage.CodalabGoogleCloudStorage(bucket_name=b'coda-public'), upload_to=b'team_logo', verbose_name=b'Logo'),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, through='teams.TeamMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
