# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-05-24 15:19
from __future__ import unicode_literals

import apps.web.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20220328_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.FileField(blank=True, null=True, storage=apps.web.utils.CodalabS3BotoStorage(), upload_to='team_logo', verbose_name='Logo'),
        ),
    ]
