# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-12-15 00:21
from __future__ import unicode_literals

import apps.web.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20180519_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.FileField(blank=True, null=True, storage=apps.web.storage.CodalabGoogleCloudStorage(bucket_name=b'codalab-gcs-public'), upload_to=b'team_logo', verbose_name=b'Logo'),
        ),
    ]
