# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-02 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20220712_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='lri-public'), upload_to='team_logo', verbose_name='Logo'),
        ),
    ]
